### PR TITLE
Fixed uninitialized constant EvilWinRM::GSSAPI error

### PR DESCRIPTION
**Pull request by Paradoxis**
Running `evil-winrm` after upgrading to 1.9 results in a `NameError`:

```
evil-winrm.rb:524 uninitialized constant EvilWinRM::GSSAPI (NameError)
```

This patch should fix this issue as the gemfile was missing gssapi as a requirement, nor was the library imported in the script

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Everything looks good, but... I have a question, how to reproduce this? in all my linux (Kali, Parrot, BlackArch) I didn't suffer that error. What kind of installation do you have on which you have not installed that ruby basic packages? are you building a Linux from the scratch? I mean, how to reproduce this? Thanks.

**Comment by Paradoxis** [comment]
@OscarAkaElvis I downloaded the latest vmware image of Kali Linux 2019.3, and installed evil-winrm into my custom tools folder:

```
$ mkdir -p /opt/tools/evil-winrm
$ GEM_HOME=/opt/tools/evil-winrm gem install evil-winrm
$ GEM_HOME=/opt/tools/evil-winrm /opt/tools/evil-winrm/bin/evil-winrm ...
```

Installing the program by itself will cause it to crash as the `gssapi` library is not installed in an empty environment (it's installed as such to isolate the tool from other projects/dependencies)

**Comment by jarilaos** [comment]
Hi @Paradoxis !

You're right, we don't consider a requirement. With the implementation of Kerberos it is necessary to have the package krb5-user installed, which depends on the library (GSSAPI) and is not installed by default.

We appreciate the pull request because we weren't aware of this, but we're going to manage it in another way, because we don't want to force to install packages of functionalities that maybe someone doesn't want to use.

Regards,

**Comment by OscarAkaElvis** [comment]
Thanks for the report, finally we are going to close this. What we'll do for the next version after some internal discussing is to remove the small piece of code which is causing this instead of add more dependencies. Anyway, we can use this thread to do tests. If you are so kind, you could do some tests for us with the dev branch content once the change is done. We'll tell to you when they are ready. 😸

**Comment by Paradoxis** [comment]
@OscarAkaElvis sure thing :)

**Comment by OscarAkaElvis** [comment]
Changes done on dev branch. Please, download it and test. It shouldn't be giving the error four you now.

**Comment by Paradoxis** [comment]
Yup seems to be working now

**Comment by OscarAkaElvis** [comment]
Awesome, thanks for the testing! 👍

**Pull request closed without merging**
