### PR TITLE
Fix undefined method exists when connection with certificate file.

### PR DESCRIPTION
**Pull request by xXxsomebodyoncetoldmexXx**
#### Describe the purpose of the pull request
When connection using certificate public and private key, evil-winrm use `exists` function which is deprecated. This will raise the error `undefined method 'exists?' for File:Class (NoMethodError)`.

The newer version of Ruby use `exist` instead of `exists`. ([ruby doc](https://ruby-doc.org/core-2.2.0/File.html#exist-3F-method))
image

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
On what Ruby version are you getting the error? from what version is this function deprecated?

Will the new `exist` function also work with older ruby versions or only with the new Ruby versions? (I didn't test this yet) if not, it could be nice to improve this to detect ruby version and depending on that, use one function or another in order to make it work in all the versions.

And the last and the most important detail about the PR, you did it to master, and sorry but we are not accepting PRs to master, only to dev branch as the PR template says (`<!--- Pull requests to master are not allowed -->`). So I'll close it and you need to do it again to dev branch and if possible, answering or improving the details discussed. Thanks.

**Comment by OscarAkaElvis** [comment]
Anyway, I can't reproduce the problem. I updated a test kali vm to the latest and is using now ruby 3.1.2p20. The problem is not happening there:

image

Could you provide more details of the issue?

**Comment by OscarAkaElvis** [comment]
Oooook, after some investigation (thanks @jarilaos), it seems the function is deprecated on Ruby 3.2.0. I modified it and did some tests using exist instead of exists and it seems everything is working on all the versions. So we decided to commit it directly into dev branch. Thanks for your contribution.

Some links talking about the deprecation and the reason: 
https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/
https://stackoverflow.com/questions/48192762/did-ruby-deprecate-the-wrong-file-exists-method

**Comment by xXxsomebodyoncetoldmexXx** [comment]
No problem, because i use the docker version so the ruby version is higher than your test bench then.
image

On the side note, I though i pull request the dev branch not the main branch? sorry i'm still a bit confuse about how pulling work.

**Comment by OscarAkaElvis** [comment]
Now you can test it using the dockerhub's image "beta" tag which is built from dev branch. It should work.

**Pull request closed without merging**
