### PR TITLE
1st pass of linting

### PR DESCRIPTION
**Pull request by noraj**
#### Describe the purpose of the pull request

I used [Rubocop](https://rubocop.org/) to make a bit of linting fixing on the main CLI script in order to follow the [Ruby Style Guide](https://rubystyle.guide/) but more importantly to make the code more readable.

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Are you really forcing me to enable MFA on my account at ruby.org??? 😧

**Comment by noraj** [comment]
> This sounds like major changes...

This only sounds, actually the changes where made with `rubocop -A` (automatic correction), so it only changed the style when it is 100% safe and compatible. https://docs.rubocop.org/rubocop/usage/autocorrect.html

I agree it's better to test but that should be 100% doing the same thing as before.

**Comment by noraj** [comment]
> Are you really forcing me to enable MFA on my account at ruby.org??? anguished

Actually yes, having TOTP 2FA for https://rubygems.org/. Nearly all package registries (rubygems, npmjs, etc.) are pushing for maintainers to enforce MFA in order to prevent supply chain attacks. Credential stuffing can happen to anyone. I have been enforcing MFA for all my gems, it's not an issue since you rarely push new release every day.

**Comment by OscarAkaElvis** [comment]
Ok, I enabled MFA in my account. But all of this needs to be checked deeply and it'll take some time.

Anyway I have more questions. I think I'll contact you at Discord to ask about them.

**Comment by OscarAkaElvis** [comment]
Please, check this because it seems you have an old version of our Gemfile where still are gem statements... in the new, there is only gemspec. Are you sure you git pulled correctly before commiting?

**Comment by noraj** [comment]
> Please, check this because it seems you have an old version of our Gemfile where still are gem statements... in the new, there is only gemspec. Are you sure you git pulled correctly before commiting?

I based this branch on the dev branch, not on master as asked in the contribution guideline. But I know why this is outdated, I sync the master branch but forgot to sync the dev branch. Let'me re-submit a PR with a up to date based dev branch.

**Pull request closed without merging**
