### PR TITLE
feat(command.split): change from .split -> shellwords.shellsplit to s…

### PR DESCRIPTION
**Pull request by ArchiMoebius**
Instead of splitting on a space - just use the stdlib shellsplit function from Shellwords

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
Hi. First, you did PR to our master branch. If your read our contribution guidelines at CONTRIBUTING.md file you'll see that we are not accepting PRs to our master branch. It should be done to dev branch. I'll add a PR template to avoid this problem in the future.

Anyway, regarding your suggested change. What is the point of it? I mean, what is it for? did you have any issue and is this fixing it? if so, maybe could be better idea to try to fix it in other way instead of adding more dependencies.

**Comment by ArchiMoebius** [comment]
Apologies for targeting wrong branch and failing to read contribution guideline.

No fun when /data directory is upload to client system during test...

# Current (3.5 / what's on master)
image

# This PR
image

[Shellwords is part of the Ruby Standard Library](https://ruby-doc.org/stdlib-2.6.5/libdoc/shellwords/rdoc/Shellwords.html). It's a [improvement over using split](https://github.com/Hackplayers/evil-winrm/pull/55/files#diff-0ad98656153cbd4d84cdc7a285f11827ddc59b82d7921552b38d70f27d9d9319L942). This isn't adding more dependencies, just using what's available.

**Comment by ArchiMoebius** [comment]
Move to https://github.com/Hackplayers/evil-winrm/pull/56

**Comment by OscarAkaElvis** [comment]
Ok, thanks for the info. Let us some time to check, test it, etc.

**Pull request closed without merging**
